### PR TITLE
[WIP] Just to see my approach to the interfaces.

### PR DESCRIPTION
**Pull request by Mistobaan**

### CODE REVIEW

**Comment by kostya-sh** [comment]
Hi @Mistobaan, thanks for the first PR! ;) To be honest it is quite big, so it is difficult to review it fully. So  I will start with a few general comments to start discussion:

I prefer to keep the public API of the library as small as possible, so:
- constants like `PARQUET_MAGIC` are ok, but they should not be exported (just `magic` is enough)
- sub-packages (such as `encoding/bitpacking` and `encoding/rle`) are not needed (or at least they should be made internal). This allows changing internals without fear of breaking other people code.

I think low level page decoders (such as rle) should have access to a byte slice with encoded data, it is not necessary to abstract it behind Reader interface because:
- it makes code much simpler (no partial reads, etc)
- it makes code faster (no interface method calls)
- decoding page data without reading it in memory first requires a lot of Seek operations and I can imagine it would be very hard to implement it.

In parquet/encoding/plain.go:
- DecodeInt is platform dependant (should be separate methods int32, int64)
- I do not think that the library should represent binary column values (even with OriginalType = UTF8) as strings because it removes a lot of optimization potential. Converting `[]byte` to string should be responsibility of the client.

General:
- to make library `go get`-friendly I'd like to avoid committing large test files into parquet-go repository. Have a look at https://github.com/kostya-sh/parquet-test that I've created for integration tests.

**Comment by kostya-sh** [comment]
Also please review my recent commits (both to parquet-go and parquet-test). I made a few fixes and improvements.

**Comment by Mistobaan** [comment]
> prefer to keep the public API of the library as small as possible, so:
> constants like PARQUET_MAGIC are ok, but they should not be exported (just magic is enough)

good point I will hide it from the public APi

> sub-packages (such as encoding/bitpacking and encoding/rle) are not needed (or at least they should be made internal). This allows changing internals without fear of breaking other people code.
> I think the format is pretty stand-alone. There is no internal detail that would bind it to 
> 
> I think low level page decoders (such as rle) should have access to a byte slice with encoded data, it is >not necessary to abstract it behind Reader interface because:
> it makes code much simpler (no partial reads, etc)
> it makes code faster (no interface method calls)
> decoding page data without reading it in memory first requires a lot of Seek operations and I can >imaging it would be very hard to implement it.
- I modeled it in the go way like [bufio.Scanner](https://golang.org/pkg/bufio/#Scanner).
- The problem with the buffer approach is that the chunk of data can be very big (thing 1GB of byte arrays). Streaming approaches are more desiderable in big data because you don't have memory trashing problems or out of memory errors. 
- All the data has a bufio.Reader that would take care of small allocations. I don't think there are many Seek operations as the underlying operative system takes care of memcpy chunks of data from disk.

> In parquet/encoding/plain.go:
> DecodeInt is platform dependant (should be separate methods int32, int64)
> good point
> 
> I do not think that the library should represent binary column values (even with OriginalType = UTF8) to strings as it removes a lot of optimization potential. This should be responsibility of the client.
> This point is not 100% clear
> 
> to make library go get-friendly I'd like to avoid committing large test files into parquet-go repository. 
> Have a look at https://github.com/kostya-sh/parquet-test that I've created for integration tests.
> Yeah I agree with that. I will move the testcases in the other repo. 

Yes the PR is big as I was working on another branch, but I wanted to share what I had done so far. I wil try to break in smaller pieces eventually.

**Comment by kostya-sh** [comment]
> The problem with the buffer approach is that the chunk of data can be very big (thing 1GB of byte arrays). Streaming approaches are more desiderable in big data because you don't have memory trashing problems or out of memory errors.

I was talking about page decoders. The current implementation is streaming. Chunk data is split in pages (the default size is 1Mb) and only one page (per column chunk) is held in memory.

> All the data has a bufio.Reader that would take care of small allocations. I don't think there are many Seek operations as the underlying operative system takes care of memcpy chunks of data from disk.

Think about typical data page layout:
- Repetition levels
- Definition levels
- Data

Levels data is always required as Data cannot be interpreted without them. If you create 3 readers (two for levels and 1 for data) on top of underlying os.File then you will have to constantly seek the underlying os.File to read all required information to decode values in parallel. And if you want to read multiple columns at the same time number of Seek calls will increase.

Reading just Data part using Reader might be possible but I prefer to keep implementation simple for now and optimize it only if necessary.

> Yes the PR is big as I was working on another branch, but I wanted to share what I had done so far. I wil try to break in smaller pieces eventually.

I am not trying to discourage your contribution but I'd like to suggest to discuss any changes (especially design and API related) to github.com/kostya-sh/parquet-go before actually implementing them. Our repositories already diverged so much that it is no longer possible to merge your work.

**Comment by kostya-sh** [comment]
> > I do not think that the library should represent binary column values (even with OriginalType = UTF8) to strings as it removes a lot of optimization potential. This should be responsibility of the client.
> 
> This point is not 100% clear

strings are immutable, so the underlying byte slice have to be always copied. `[]byte` instances on other hand can share content (though it makes API a bit harder to use correctly).

**Comment by vrecan** [comment]
is this dead? 

The company I am working for needs to read and write parquet files preferably in go. We could potentially help with this.

**Comment by kostya-sh** [comment]
@vrecan, I am not actively working on this package as I have no use for it. I started this project mainly to learn more about parquet format and Go language.

If your company needs a Go library that can read/write parquet files the best way would be to fork the repo and start from there. Alternatevely you might want to:
- use CGo to provide Go interface to the existing "official" C++ parquet library.
- use parquet-mr library written in Java.

If you decide to work on the open source parquet Go implementation I will be happy to help and answer any questions.

**Pull request closed without merging**
